apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: akk06ra2q-go 
  janus-idp.io/tekton: akk06ra2q-go
  backstage.io/kubernetes-id: akk06ra2q-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: akk06ra2q-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  